# Generated by Django 4.0.8 on 2024-04-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='users',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='customer_resources',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='user_role_privileges',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
    ]
